# Generated by Django 5.2.11 on 2026-08-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metric', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(choices=[('bio', 'Developer Bio & Background'), ('skill', 'Skills & Technical Stack'), ('project', 'Projects & Engineering'), ('cv', 'CV & Career History'), ('contact', 'Contact & Socials'), ('services', 'Services & Contracting'), ('general', 'General Knowledge')], default='general', max_length=50)),
                ('keywords', models.JSONField(default=list, help_text='Keywords list for matching query intent')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Knowledge Document',
                'verbose_name_plural': 'AI Knowledge Documents',
                'ordering': ['-priority', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, default='', max_length=100)),
                ('credential_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('start_year', models.IntegerField(default=2020)),
                ('end_year', models.IntegerField(default=2023)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(default='Remote / Kerala, India', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('bullet_points', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Suryakiran P. J.', max_length=150)),
                ('role', models.CharField(default='Python Full Stack Developer', max_length=200)),
                ('tagline', models.TextField(default='Building modern, responsive and scalable web experiences with Python, Django, and React.')),
                ('summary', models.TextField(default='Enthusiastic Python Full Stack Developer with strong expertise in building RESTful APIs, relational database design, and dynamic React user interfaces.')),
                ('email', models.EmailField(default='suryakiranpjineesh@gmail.com', max_length=254)),
                ('location', models.CharField(default='Kerala, India', max_length=150)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(default='https://github.com/skiran-ai')),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/in/surya-kiran-967659351')),
                ('instagram_url', models.URLField(default='https://www.instagram.com/jstt.kiran')),
                ('resume_pdf_url', models.URLField(blank=True, default='/assets/Suryakiran-PJ-CV.pdf')),
                ('availability', models.CharField(default='Available for Full-time & Remote Roles', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('icon_name', models.CharField(default='Layers', max_length=50)),
                ('technologies', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_mode', models.CharField(choices=[('PUBLIC', 'PUBLIC MODE - Full Access'), ('MAINTENANCE', 'MAINTENANCE MODE - Scheduled Maintenance'), ('PRIVATE', 'PRIVATE MODE - System Shielded')], default='PUBLIC', max_length=20)),
                ('maintenance_message', models.TextField(default='System maintenance in progress. Public endpoints are temporarily restricted.')),
                ('allow_contact_form', models.BooleanField(default=True)),
                ('allow_ai_assistant', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting & Privacy Control',
                'verbose_name_plural': 'Site Settings & Privacy Control',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('tools', 'Tools & DevOps'), ('development', 'Core Development')], max_length=50)),
                ('badge', models.CharField(blank=True, default='', help_text='e.g. Hooks & Component Architecture', max_length=150)),
                ('icon_name', models.CharField(default='Code', help_text='Lucide React icon name', max_length=50)),
                ('proficiency', models.PositiveIntegerField(default=90, help_text='Percentage 1-100')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_name', models.CharField(default='Globe', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='backend_tech',
            field=models.CharField(blank=True, default='Python 3.11+, Django 4.2+, Django REST Framework', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='database_tech',
            field=models.CharField(blank=True, default='PostgreSQL / SQLite ORM', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='deployment_tech',
            field=models.CharField(blank=True, default='Netlify CDN + Django Cloud API', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='frontend_tech',
            field=models.CharField(blank=True, default='React 18, Vite, Bootstrap 5, Lucide Icons', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('AI/ML', 'AI / Machine Learning'), ('DevOps', 'DevOps & Cloud')], max_length=50),
        ),
    ]
