databases:
  - name: suryakiran-portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: free

services:
  - type: web
    name: suryakiran-portfolio-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py seed_portfolio && python manage.py collectstatic --noinput"
    startCommand: "gunicorn portfolio_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: suryakiran-portfolio-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
